### ISSUE TITLE
[CONFIG] Using multi source throws `reduce is not a function`

### ISSUE THREAD

**Issue by darionco** [purtuga/esm-webpack-plugin#1]
If an array is used in the `entry` field of the webpack build configuration then `reduce is not a function` is thrown. Even if it's a single file:

```
const EsmWebpackPlugin = require("esm-webpack-plugin");

module.exports = {
    mode: "development",
    entry: ["index.js"],
    output: {
        library: "LIB",
        libraryTarget: "var"
    },
    //...
    plugins: [
        new EsmWebpackPlugin()
    ]
}
```

**Comment by darionco** [comment]
Also, when used with `webpack-dev-server`

**Comment by purtuga** [comment]
Hi @darionco  - thanks for reporting this.
I'm not sure yet how that can be resolved.  Could you comment out the plugin in your config. and run your webpack command with these two options and let me know what you see get: `--bail --display-optimization-bailout`

**Comment by darionco** [comment]
Hi, I really need it fixed so I created PR #2 , if you could review it and publish the change (if it's good) I would really appreciate it.

Thanks!

**Comment by purtuga** [comment]
That's Awesome @darionco - Really appreciate that... Reviewing it now.

**Comment by purtuga** [comment]
Thanks again... Just published a patch: https://www.npmjs.com/package/@purtuga/esm-webpack-plugin

**Comment by darionco** [comment]
Perfect, thank you so much for your quick response!
