### ISSUE TITLE
Support for externals

### ISSUE THREAD

**Issue by internettrans** [purtuga/esm-webpack-plugin#18]
Thanks for your work on this library. I'm looking forward to webpack 5 supporting libraryTarget `"module"`, but am interested in getting support for webpack externals within esm-webpack-plugin while I wait for that.

Would you be open to a pull request that adds support for externals? I authored the [SystemLibraryPlugin](https://github.com/webpack/webpack/blob/master/lib/library/SystemLibraryPlugin.js) within webpack and have some experience in working with externals inside of webpack.

### Desired behavior

```js
// webpack.config.js
module.exports = {
  externals: ['react', 'react-dom'],
  plugins: [new EsmWebpackPlugin()]
}
```

```js
// index.js
import * as React from 'react';
import * as ReactDOM from 'react-dom';

ReactDOM.render(<Root />, document.getElementById('root'))
```

```js
// bundle.js
import * as __WEBPACK_EXTERNAL_MODULE_0 from 'react';
import * as __WEBPACK_EXTERNAL_MODULE_0 from 'react-dom';

// now inject into webpack module registry, etc
```

**Comment by purtuga** [comment]
Hi @joeldenning . Thanks for suggesting adding this functionality to this plugin. I certainly would be open to it. 

Q. Why would you have to inject it into the bundle's webpack module registry?

I don't recall having used `externals` before, but I assume this is needed due to how the `import` is compiled for an external library (I'm guessing its compiled to a webpack `required` module load?)

Thanks again for your suggestion and looking forward to the PR/contribution.

**Comment by internettrans** [comment]
> Q. Why would you have to inject it into the bundle's webpack module registry?

Good question. As I look into this more, perhaps injecting into the module registry is not the right way to describe it, since the `libraryTarget` is `var`, which references externals as global variables.

For example, consider the following output which was generated with webpack 5 on the index.js file I showed above: https://gist.github.com/joeldenning/4f8fdd79ab6110c6dc46e607473ecb7d

In that example, `react` and `react-dom` are referenced as global variables, since that's how `var` externals are implemented. One implementation approach for esm-webpack-plugin could be to import react/react-dom with the same names as the global variables. Another implementation approach is to modify the names of the "global" variables to be something like `__WEBPACK_EXTERNAL_0__` and then import the externals under those names

```js
/***/ "react":
/*!************************!*\
  !*** external "react" ***!
  \************************/
/*! unknown exports (runtime-defined) */
/*! runtime requirements: module */
/***/ ((module) => {

module.exports = react;

/***/ }),

/***/ "react-dom":
/*!****************************!*\
  !*** external "react-dom" ***!
  \****************************/
/*! unknown exports (runtime-defined) */
/*! runtime requirements: module */
/***/ ((module) => {

module.exports = react-dom;

/***/ })
```
