### ISSUE TITLE
Request updates for webpack 5

### ISSUE THREAD

**Issue by fuweichin** [purtuga/esm-webpack-plugin#21]
As webpack 5 released, some of its dependents released updates.  
```txt
npm view webpack-cli peerDependencies
{ webpack: '4.x.x || 5.x.x' }
npm view webpack-dev-server peerDependencies
{ webpack: '^4.0.0 || ^5.0.0' }
```

`@purtuga/esm-webpack-plugin`  is not currently compatible with `webpack` 5 although it declares to be
```txt
npm view @purtuga/esm-webpack-plugin peerDependencies
{ webpack: '>= 4.0.0' }
```
In `@purtuga\esm-webpack-plugin\esm-webpack-plugin.js`

> Error: Cannot find module 'webpack/lib/MultiModule'

**Additional Information:**
+ @purtuga/esm-webpack-plugin 1.4.0
+ webpack 5.1.0

**Comment by purtuga** [comment]
Thanks for posting this @fuweichin and for making aware that Webpack had release 5.0 - did not know that.

I'm thinking this would be the fix for this plugin:

```json
  "peerDependencies": {
    "webpack": "^4.0.0"
  },
```

You agree?

Note that I don't plan on having support for this plugin in webpack 5, since that version of Webpack is meant to support ESM output bundles

**Comment by icyfanfan** [comment]
ESM output bundles supportting doc can be found [here](https://webpack.js.org/configuration/output/#outputmodule)

**Comment by purtuga** [comment]
I have fixed this by releasing v1.4.1. webpack peerDependency has been changed to support only v4. Readme file was also updated and a important notice

**Comment by vapier** [comment]
ftr, esm library output is **not** in webpack 5 (including the current 5.2.0 release).  see https://github.com/webpack/webpack/issues/2933.

hopefully it'll happen at some point, but that point is not now :/.

**Comment by xinaesthete** [comment]
Further to the above comment, the text in the readme stating that 'Webpack 5 has been released and with it comes support for output ES Modules' sent me on a bit of a wild-goose chase.

**Comment by purtuga** [comment]
@xinaesthete sorry for the trouble that documentation has cause you. I will update it now to indicate that support is not yet implemented in 5.x of webpack.

That being said, I currently don't plan to release a version of this plugin for webpack 5, as I just don't have the time to look into what is necessary to support it. I would certainly entertain a contribution that would move this plugin in that direction though 🙂

**Comment by xinaesthete** [comment]
@portuga, no worries.  I think your position is reasonable wrt Webpack 5, anyway.  For now I seem to have found another way, but wouldn't rule out maybe contributing a patch if I get a rush of blood to the head (don't hold your breath :wink:).

**Comment by thescientist13** [comment]
@xinaesthete 
What was the other way you were able to arrive at?

**Comment by xinaesthete** [comment]
@thescientist13 I think in this case it was using `esbuild` instead... this whole JS build-tool situation is a major factor in me not bothering to get back to various projects where I never quite got things set up quite right though, TBH. So many hours of my life wasted on this nonsense.

On the whole, I think I've been most happy with Vite FWIW.

**Comment by xinaesthete** [comment]
I don't mean to disparage the efforts of anyone who's worked hard on contributing to the ecosystem - I'm sure in many instances it's my own misguided over-engineering that's got me into a pickle...

**Comment by purtuga** [comment]
@xinaesthete completely understand and can relate. No worries. No offense taken here 😄

**Comment by thescientist13** [comment]
Thanks for the info @xinaesthete .

In my case, I am evaluating Single SPA and was following their [example here](https://github.com/isomorphic-microfrontends) and noticed that it uses webpack v4, but had some issues when trying to use it with webpack v5, which lead me to this issue.

Hoping that ESM support comes to webpack as my workplace is using webpack.  😅 🤞

**Comment by mayankmishra2812** [comment]
@thescientist13 : Did you get any other solution, as my workplace is also using webpack only. We are also facing similar sort of problem and looking for a solution.

**Comment by thescientist13** [comment]
hey @mayankmishra2812 , no unfortunately I did not find a resolution to this, so ended up going with another approach to my problem.
