### ISSUE TITLE
Cannot read property 'nameForCondition' of null

### ISSUE THREAD

**Issue by equicy** [purtuga/esm-webpack-plugin#24]
const moduleName = typeof module.nameForCondition === 'function'

**Comment by purtuga** [comment]
🤷‍♂️

**Comment by EricRabil** [comment]
I'm running into this as well, but only if I have additional entry points.

**EDIT**: If you're seeing this error, it's likely that the path to the given entry point is invalid. This is not an issue with esm-webpack-plugin.
