### ISSUE TITLE
"@purtuga/esm-webpack-plugin"

### ISSUE THREAD

**Issue by jhchance** [purtuga/esm-webpack-plugin#3]
In Windows, It should be require "@purtuga/esm-webpack-plugin" in the webpack config js file.

**Comment by purtuga** [comment]
Yes.  You right.
Just to make sure - you are referring to the instructions/example in the README file, correct? Or something else?

Thanks for repointing this.

**Comment by laggingreflex** [comment]
I came to know about this plugin from [this article](https://paultavares.wordpress.com/2018/07/02/webpack-how-to-generate-an-es-module-bundle/) where it also says just "esm-webpack-plugin"

Edit: Nevermind, on closer look, it does mention `@purtuga/` in npm install command. My bad
