### ISSUE TITLE
Only works when the source is ESM? 

### ISSUE THREAD

**Issue by laggingreflex** [purtuga/esm-webpack-plugin#9]
It seems it only works when the source exports are in ESM format. Is that intentional? If not, please consider this a feature request.

**Comment by purtuga** [comment]
~You seem to have opened multiple issues. Since #11 seems to have a more complete description, I'm closing this out. I will comment on #11.~

**Comment by purtuga** [comment]
@laggingreflex  - My fault. Just analyzed your pull request and I now understand the issue.

You are correct that the initial intent was for this to support only ESM source. That being said, I don't have an issue adding support for CJS. I will take some time to setup a simple project to recreate the condition and analyze what webpack returns back.

Thanks for reporting it and providing a fix. Will come back here soon.
